// Code generated by Arduino IoT Cloud, DO NOT EDIT.

#include <ArduinoIoTCloud.h>
#include <Arduino_ConnectionHandler.h>

const char SSID[]     = SECRET_SSID;    // Network SSID (name)
const char PASS[]     = SECRET_PASS;    // Network password (use for WPA, or use as key for WEP)

void onCountdownChange();
void onHoursChange();
void onMinutesChange();
void onSecondsChange();

int countdown_;
int hours_;
int minutes_;
int seconds_;
bool led;

void initProperties(){

  ArduinoCloud.addProperty(countdown_, READWRITE, ON_CHANGE, onCountdownChange);
  ArduinoCloud.addProperty(hours_, READWRITE, ON_CHANGE, onHoursChange);
  ArduinoCloud.addProperty(minutes_, READWRITE, ON_CHANGE, onMinutesChange);
  ArduinoCloud.addProperty(seconds_, READWRITE, ON_CHANGE, onSecondsChange);
  ArduinoCloud.addProperty(led, READ, ON_CHANGE, NULL);

}

WiFiConnectionHandler ArduinoIoTPreferredConnection(SSID, PASS);
