#include "arduino_secrets.h"
/* 
  Sketch generated by the Arduino IoT Cloud Thing "Untitled"
  https://create.arduino.cc/cloud/things/0b917690-7725-4416-8531-f40694515578 

  Arduino IoT Cloud Variables description

  The following variables are automatically generated and updated when changes are made to the Thing

  int countdown_;
  int hours_;
  int minutes_;
  int seconds_;
  bool led;

  Variables which are marked as READ/WRITE in the Cloud Thing will also have functions
  which are called when their values are changed from the Dashboard.
  These functions are generated with the Thing and added at the end of this sketch.
*/

#include "thingProperties.h"

void setup() {
  // Initialize serial and wait for port to open:
  Serial.begin(9600);
  // This delay gives the chance to wait for a Serial Monitor without blocking if none is found
  delay(1500); 

  // Defined in thingProperties.h
  initProperties();

  // Connect to Arduino IoT Cloud
  ArduinoCloud.begin(ArduinoIoTPreferredConnection);
  
  /*
     The following function allows you to obtain more information
     related to the state of network and IoT Cloud connection and errors
     the higher number the more granular information you’ll get.
     The default is 0 (only errors).
     Maximum is 4
 */
  setDebugMessageLevel(2);
  ArduinoCloud.printDebugInfo();
}

void loop() {
  ArduinoCloud.update();
  // Your code here 
  
  
}



/*
  Since CountDown is READ_WRITE variable, onCountDownChange() is
  executed every time a new value is received from IoT Cloud.
*/
void onCountDownChange()  {
  // Add your code here to act upon CountDown change
}

/*
  Since Hours is READ_WRITE variable, onHoursChange() is
  executed every time a new value is received from IoT Cloud.
*/
void onHoursChange()  {
  // Add your code here to act upon Hours change
}

/*
  Since Minutes is READ_WRITE variable, onMinutesChange() is
  executed every time a new value is received from IoT Cloud.
*/
void onMinutesChange()  {
  // Add your code here to act upon Minutes change
}

/*
  Since Seconds is READ_WRITE variable, onSecondsChange() is
  executed every time a new value is received from IoT Cloud.
*/
void onSecondsChange()  {
  // Add your code here to act upon Seconds change
}

/*
  Since Countdown is READ_WRITE variable, onCountdownChange() is
  executed every time a new value is received from IoT Cloud.
*/
void onCountdownChange()  {
  // Add your code here to act upon Countdown change
}

